### ISSUE TITLE
Tensorflow Errors with fresh install

### ISSUE THREAD

**Issue by Cryaaa** [LabTrivedi/MOrgAna#1]
Hello,
I'm trying to train the MLP classifier for some organoid data but I'm having trouble with some errors. I'm using the default values when you open the morgana gui for training but I have chosen the daisy features. It seems to start the training as expected and I can see the progress of the epochs. Once it is done it throws this error

```
Models trained in 69.889 seconds.
2022-11-23 15:42:40.981313: W tensorflow/core/framework/op_kernel.cc:1780] OP_REQUIRES failed at save_restore_v2_ops.cc:112 : NOT_FOUND: Failed to create a NewWriteableFile: C:/Users/ryans/OneDrive/Documents/PhD Jesse/Playing around with Data/DATA_raw_and_processed/all_sample_annotated_101122/Trying out morgana/morgana_test/DL model/model\variables\variables_temp/part-00000-of-00001.data-00000-of-00001.tempstate12651736733115838873 : The system cannot find the path specified.
; No such process
Traceback (most recent call last):
  File "C:\Users\ryans\Anaconda3\envs\morgana_env\lib\site-packages\morgana\GUIs\mainwindow.py", line 415, in trainModel
    ioML.save_model( self.modelFolder,
  File "C:\Users\ryans\Anaconda3\envs\morgana_env\lib\site-packages\morgana\MLModel\io.py", line 28, in save_model
    classifier.save(os.path.join(model_folder))
  File "C:\Users\ryans\Anaconda3\envs\morgana_env\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ryans\Anaconda3\envs\morgana_env\lib\site-packages\tensorflow\python\eager\execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError: {{function_node __wrapped__SaveV2_dtypes_28_device_/job:localhost/replica:0/task:0/device:CPU:0}} Failed to create a NewWriteableFile: C:/Users/ryans/OneDrive/Documents/PhD Jesse/Playing around with Data/DATA_raw_and_processed/all_sample_annotated_101122/Trying out morgana/morgana_test/DL model/model\variables\variables_temp/part-00000-of-00001.data-00000-of-00001.tempstate12651736733115838873 : The system cannot find the path specified.
; No such process [Op:SaveV2]
```

I set up the environment with conda, python=3.9 and installed tensorflow 2.10 after installing cudatoolkit=11.2 cudnn=8.1.0
I then installed morgana but got an error that pyQT5 was missing, so I installed pyqt with pip afterwards. Nothing else is installed in the environment.

**Comment by grinic** [comment]
Hello,
We have never seen this error before and I suspect this is an incompatibility on the python side.

could you give us a few more information?
1. How have you setup the environment (with or without the yml file provided)
2. Which OS are you using (from the path name I gather you are using Windows?)
3. Could you please try to use a shorter path length by removing some parts of the folder names? Looking for example [HERE](https://stackoverflow.com/questions/45076911/tensorflow-failed-to-create-a-newwriteablefile-when-retraining-inception) there is a max length for paths in windows.

**Comment by Cryaaa** [comment]
Thanks for the quick reply! I set up a fresh conda environment and then installed the packages, I mentioned and yes I am on windows. 

I just tried to shorten the path length and that fixed it! Thanks for the quick help!
